language: node_js
node_js: "15"
cache: npm
jobs:
  include:
    - stage: test
      script:
        - "npm install"
        - "npm run build"
        - "npm start"
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true        
